
# Data
use_Kitti: True
use_Malaga: False
use_ISARLAB_CAR: False
use_subsampled: True
input_width: 1226 #KITTI: 1226 - Malaga:1024
input_height: 376
input_channel: 3


# Training / test parameters
is_train: True
strategy: uavo
continue_train: False
start_epoch: 0        #Epoch at which training starts. If resume_train is True, it should be set to the epoch that refers to the desired checkpoint
exp_name: uavo_sgd
train_set_name: KITTIRGB_376x1226 # ISARLABCAR_376x1226, MALAGA_376x1024
test_set_name: KITTIRGB_376x1226 #
random_seed: 409
init_lr: 0.01
init_lr_mean: 0.01
init_lr_std: 0.001
timesteps: 5
stochastic_sample: 20
drop_prob: 0.2
checkpoint_step: 5
optimizer: sgd        #SGD or Adam
ram_pre_loading: False
max_epochs: 201
batch_size: 4
lr_policy: step        #lambda|step|plateau
lr_decay_iters: 10
lr_step_gamma: 0.8
start_train_std: 80
lr_std: 0.001

# Misc
print_freq: 1
display_freq: 100
save_epoch_freq: 20
test_epoch_freq: 20
num_workers: 16
gpu_id: 0

